### ISSUE TITLE
spring-netty-example 请求出现异常

### ISSUE THREAD

**Issue by Wilfred-Aha** [wangzihaogithub/spring-boot-protocol#1]
ERROR 8220 --- [-Worker-NIO-3-3] c.g.n.p.servlet.ServletChannelHandler    : java.lang.ClassCastException: javax.servlet.http.Cookie cannot be cast to java.lang.Comparable

**Comment by wangzihaogithub** [comment]
谢谢你, 估计是java-servlet的版本问题.  我尽快排查一下.

**Comment by Wilfred-Aha** [comment]
这个netty-servlet 和 spring-boot-protocol

**Comment by Wilfred-Aha** [comment]
这个netty-servlet 和 spring-boot-protocol 哪个是最新的版本

**Comment by wangzihaogithub** [comment]
git上的spring-boot-protocol 是最新的版本,只不过最新版使用的话需要你maven install一下. 

@EnableNettyServletEmbedded注解名变为了 @EnableNettyEmbedded
![image](https://user-images.githubusercontent.com/18204507/68638718-5bd43800-053d-11ea-899a-61e1b593def5.png)


maven上的spring-boot-protocol是8月份的版本

![image](https://user-images.githubusercontent.com/18204507/68638555-ea948500-053c-11ea-9253-610cdd4b1fe9.png)

**Comment by wangzihaogithub** [comment]
我现在就把最新版(spring-boot-protoco 2.0.3)发布到maven中央仓库.

**Comment by Wilfred-Aha** [comment]
嗯, 谢谢.  我下下来自己先学习下.

**Comment by Wilfred-Aha** [comment]
### 你好,麻烦再帮我看下这个问题,谢谢
我运行netty-example-servlet实例的时候,使用postman请求接口,一直出现下面这个错误.

ava.io.IOException: 你的主机中的软件中止了一个已建立的连接。
	at sun.nio.ch.SocketDispatcher.write0(Native Method) ~[na:1.8.0_121]
	at sun.nio.ch.SocketDispatcher.write(Unknown Source) ~[na:1.8.0_121]
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(Unknown Source) ~[na:1.8.0_121]
	at sun.nio.ch.IOUtil.write(Unknown Source) ~[na:1.8.0_121]
	at sun.nio.ch.SocketChannelImpl.write(Unknown Source) ~[na:1.8.0_121]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:408) ~[netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:898) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1384) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.handler.logging.LoggingHandler.flush(LoggingHandler.java:265) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:533) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:358) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:328) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:133) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at com.github.netty.protocol.servlet.ServletOutputChunkedStream.asyncFlush(ServletOutputChunkedStream.java:61) [classes/:na]
	at com.github.netty.protocol.servlet.ServletOutputChunkedStream.close(ServletOutputChunkedStream.java:41) [classes/:na]
	at com.github.netty.protocol.servlet.ServletOutputStream.recycle(ServletOutputStream.java:413) [classes/:na]
	at com.github.netty.protocol.servlet.ServletOutputStreamWrapper.recycle(ServletOutputStreamWrapper.java:123) [classes/:na]
	at com.github.netty.protocol.servlet.ServletHttpServletResponse.recycle(ServletHttpServletResponse.java:482) [classes/:na]
	at com.github.netty.protocol.servlet.ServletHttpExchange.recycle(ServletHttpExchange.java:160) [classes/:na]
	at com.github.netty.protocol.servlet.NettyMessageToServletRunnable$HttpRunnable.run(NettyMessageToServletRunnable.java:135) [classes/:na]
	at com.github.netty.protocol.servlet.ServletChannelHandler.onMessageReceived(ServletChannelHandler.java:43) [classes/:na]
	at com.github.netty.core.AbstractChannelHandler.channelRead(AbstractChannelHandler.java:45) [classes/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at com.github.netty.metrics.MessageMetricsChannelHandler.onMessageReceived(MessageMetricsChannelHandler.java:50) [classes/:na]
	at com.github.netty.core.AbstractChannelHandler.channelRead(AbstractChannelHandler.java:45) [classes/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at com.github.netty.metrics.BytesMetricsChannelHandler.onMessageReceived(BytesMetricsChannelHandler.java:51) [classes/:na]
	at com.github.netty.metrics.BytesMetricsChannelHandler.onMessageReceived(BytesMetricsChannelHandler.java:1) [classes/:na]
	at com.github.netty.core.AbstractChannelHandler.channelRead(AbstractChannelHandler.java:45) [classes/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at com.github.netty.protocol.DynamicProtocolChannelHandler.onMessageReceived(DynamicProtocolChannelHandler.java:86) [classes/:na]
	at com.github.netty.protocol.DynamicProtocolChannelHandler.onMessageReceived(DynamicProtocolChannelHandler.java:1) [classes/:na]
	at com.github.netty.core.AbstractChannelHandler.channelRead(AbstractChannelHandler.java:45) [classes/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_121]
	at com.github.netty.core.util.NettyThreadX.run(NettyThreadX.java:49) [classes/:na]

**Comment by wangzihaogithub** [comment]
好的, 我看一下. 这个应该是postman客户端非常规断开HTTP连接导致的提示信息,  是正常的.
 只是看起来比较奇怪, 我把错误提示对标tomcat的提示修改一下.

**Comment by wangzihaogithub** [comment]
> ERROR 8220 --- [-Worker-NIO-3-3] c.g.n.p.servlet.ServletChannelHandler : java.lang.ClassCastException: javax.servlet.http.Cookie cannot be cast to java.lang.Comparable

你用的应该maven中央仓库的代码版本, 我已经在19年6月10日解决这个问题了.新版是没问题的.

我预计11月17日前将新版发布到maven中央仓库



[ 点击查看该问题的git补丁记录](https://github.com/wangzihaogithub/spring-boot-protocol/commit/2a2cf820f47a859537d41c2e201f22c1a0470fec?diff=unified#diff-ff60570574c4779fede0b0f1c0cbd742)




![image](https://user-images.githubusercontent.com/18204507/68650542-34db2d80-0560-11ea-93be-269923786497.png)

![image](https://user-images.githubusercontent.com/18204507/68650344-b8e0e580-055f-11ea-906a-eebecbe96e63.png)
![image](https://user-images.githubusercontent.com/18204507/68650849-f134f380-0560-11ea-8afb-0f2b0ae3ea29.png)

**Comment by wangzihaogithub** [comment]
欢迎下次交流
下次可以尝试新开一个 Issue.

**Comment by Wilfred-Aha** [comment]
嗯,谢谢
但是我直接依赖的是最新的spring-boot-protocol项目,没有使用maven库里面的.
现在的异常是:  java.io.IOException: 你的主机中的软件中止了一个已建立的连接。

**Comment by wangzihaogithub** [comment]
你好, 用postman总提示主机终止连接, 已经发现问题并解决了. 解决在了master分支

https://github.com/wangzihaogithub/spring-boot-protocol/issues/1#issuecomment-552758729

**Comment by Wilfred-Aha** [comment]
嗯, 谢谢大佬. 辛苦大佬了.
