### ISSUE TITLE
FileUpload OutOfDirectMemoryError

### ISSUE THREAD

**Issue by markbanyang** [wangzihaogithub/spring-boot-protocol#12]
servlet handler exception. case=io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 234881024 byte(s) of direct memory (used: 247463943, max: 477626368), channel=[id: 0x2ef2a55c, L:/127.0.0.1:10002 - R:/127.0.0.1:53528]

io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 234881024 byte(s) of direct memory (used: 247463943, max: 477626368)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:754) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:709) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:645) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.buffer.PoolArena$DirectArena.newUnpooledChunk(PoolArena.java:635) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.buffer.PoolArena.allocateHuge(PoolArena.java:215) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:143) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.buffer.PoolArena.reallocate(PoolArena.java:288) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:118) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:306) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:282) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1104) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1097) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1088) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:340) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:52) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at com.github.netty.protocol.servlet.ServletInputStreamWrapper.onMessage(ServletInputStreamWrapper.java:109) ~[classes/:na]
	at com.github.netty.protocol.servlet.NettyMessageToServletRunnable.onMessage(NettyMessageToServletRunnable.java:84) ~[classes/:na]
	at com.github.netty.core.DispatcherChannelHandler.onMessageReceived(DispatcherChannelHandler.java:32) ~[classes/:na]
	at com.github.netty.core.AbstractChannelHandler.channelRead(AbstractChannelHandler.java:42) ~[classes/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
	at com.github.netty.core.util.NettyThreadX.run(NettyThreadX.java:49) [classes/:na]

**Comment by wangzihaogithub** [comment]
我看下 , 估计明天上午解决

**Comment by wangzihaogithub** [comment]
解决了. 在这次提交, 已经合并到master分支了, 也已经提交到maven中央仓库了. 过两天就同步到中央仓库了. 

原因是: 错误的将netty的HttpPostMultipartRequestDecoder 的 discardThreshold参数设置成了Integer.MAX_VALUE导致的.


public int getDiscardThreshold(){
        int discardThreshold = 0;
        if(multipartConfigElement != null) {
            discardThreshold = (int)multipartConfigElement.getMaxFileSize();
        }
        if(discardThreshold <= 0){
            discardThreshold = Integer.MAX_VALUE; //就是这里, 这个参数是控制复制文件的缓冲区, 我现在改成了不设置, 即netty默认的最大10M.
        }
        return discardThreshold;
    }


https://github.com/wangzihaogithub/spring-boot-protocol/commit/d65fe249948bb39ea437831850b1f4b27b081a1d

**Comment by markbanyang** [comment]
我验证了下，上传文件OOM的问题已经解决了。

**Comment by markbanyang** [comment]
另外我在测试下载大文件的时候，耗时比tomcat长很多，从抓取的数据包发现，下载文件的时候发送一部分包后，会等待一段时间才会继续发送下一个包：
![image](https://user-images.githubusercontent.com/48742762/101234992-51b04900-36ff-11eb-80ad-5af42c4cfd78.png)
![image](https://user-images.githubusercontent.com/48742762/101234994-5412a300-36ff-11eb-9718-7fdea9759b3b.png)


下面是我的测试代码：
`    @RequestMapping("/file-download-test")
    public ResponseEntity<String> downloadFile(HttpServletRequest request, HttpServletResponse response) throws Exception {
        String fileName = "CentOS-7-x86_64-DVD-2003.iso";
        String filePath = "./" + fileName;
        handleDownloadStream(fileName, filePath, request, response);
        return new ResponseEntity<>(HttpStatus.OK);
    }

public void handleDownloadStream(String fileName, String filePath, HttpServletRequest request, HttpServletResponse res) throws IOException {
        byte[] buffer = new byte[4 * 1024];
        OutputStream os = null;
        FileInputStream fStream = null;
        try {
            os = new BufferedOutputStream(res.getOutputStream());
            res.reset();
            String agent = request.getHeader("User-Agent");
            if (agent == null) {
                return;
            }
            agent = agent.toUpperCase();

            //ie浏览器,火狐,Edge浏览器
            if (agent.indexOf("MSIE") > 0 || agent.indexOf("RV:11.0") > 0 || agent.indexOf("EDGE") > 0 || agent.indexOf("SAFARI") > -1) {
                fileName = URLEncoder.encode(fileName, "utf8").replaceAll("\\+", "%20");
            } else {
                fileName = new String(fileName.getBytes(StandardCharsets.UTF_8), "ISO8859_1");
            }
            //safari RFC 5987标准
            if (agent.indexOf("SAFARI") > -1) {
                res.addHeader("content-disposition", "attachment;filename*=UTF-8''" + fileName);
            } else {
                res.addHeader("Content-disposition", "attachment; filename=\"" + fileName + '"');
            }
            File file = new File(filePath);
            res.setContentType("application/octet-stream");
            res.setCharacterEncoding("UTF-8");
            res.setContentLength((int) file.length());
            fStream = new FileInputStream(file);
            int length = 0;
            while ((length = fStream.read(buffer)) != -1) {
                os.write(buffer, 0, length);
            }
            os.flush();

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
//            os.close();
            IOUtils.closeQuietly(fStream);
        }
    }
`

**Comment by wangzihaogithub** [comment]
这是由这个参数控制的， 你可以改成1KB。默认达到是1M后，再给客户端发数据。

server.netty.http-servlet.response-max-buffer-size=1024

**Comment by wangzihaogithub** [comment]
我下个版本把默认值改小点，另外， 你可以这样发文件，性能会好一些，因为用的是netty的零拷贝

 try(NettyOutputStream outputStream = (NettyOutputStream)response.getOutputStream()){
                outputStream.write(new File("/home/temp.json"));
            } catch (IOException e) {
                e.printStackTrace();
            }

**Comment by markbanyang** [comment]
好的 我尝试下

**Comment by markbanyang** [comment]
文件下载是否存在内存不释放的问题，配置启动内存-Xmx512M -XX:MaxDirectMemorySize=512M，下载一个不到2G文件会卡住，并且会将分配的内存耗尽。
![image](https://user-images.githubusercontent.com/48742762/101237040-b88a2e00-3710-11eb-9b47-e063542dccf7.png)
![image](https://user-images.githubusercontent.com/48742762/101237046-ca6bd100-3710-11eb-9cf1-f45649ba7e34.png)

**Comment by wangzihaogithub** [comment]
可以看下代码吗？ 我用的你第一次的代码复现不出来。


master分支的这个类 com.github.netty.http.example.HttpController， 是我用的例子， 不知道一样不

`


   @RequestMapping("/downloadFile")
   public ResponseEntity<String> downloadFile(HttpServletRequest request, HttpServletResponse response) throws Exception {
        String fileName = "CentOS-7-x86_64-DVD-2003.iso";

        byte[] file = new byte[1024 * 1024 * 7];
        for (int i = 0; i < file.length; i++) {
            file[i] = (byte) i;
        }
        handleDownloadStream(fileName, new ByteArrayInputStream(file), request, response);
        return new ResponseEntity<>(HttpStatus.OK);
    }

    public void handleDownloadStream(String fileName, InputStream inputStream, HttpServletRequest request, HttpServletResponse res) throws IOException {
        byte[] buffer = new byte[4 * 1024];
        OutputStream os = null;
        try {
            os = new BufferedOutputStream(res.getOutputStream());
            res.reset();
            String agent = request.getHeader("User-Agent");
            if (agent == null) {
                return;
            }
            agent = agent.toUpperCase();

            //ie浏览器,火狐,Edge浏览器
            if (agent.indexOf("MSIE") > 0 || agent.indexOf("RV:11.0") > 0 || agent.indexOf("EDGE") > 0 || agent.indexOf("SAFARI") > -1) {
                fileName = URLEncoder.encode(fileName, "utf8").replaceAll("\\+", "%20");
            } else {
                fileName = new String(fileName.getBytes(StandardCharsets.UTF_8), "ISO8859_1");
            }
            //safari RFC 5987标准
            if (agent.contains("SAFARI")) {
                res.addHeader("content-disposition", "attachment;filename*=UTF-8''" + fileName);
            } else {
                res.addHeader("Content-disposition", "attachment; filename=\"" + fileName + '"');
            }
            res.setContentType("application/octet-stream");
            res.setCharacterEncoding("UTF-8");
            res.setContentLength(inputStream.available());
            int length = 0;
            while ((length = inputStream.read(buffer)) != -1) {
                os.write(buffer, 0, length);
            }
            os.flush();

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            IOUtils.closeQuietly(inputStream);
        }
    }
`

com.github.netty.http.example

**Comment by wangzihaogithub** [comment]
辛苦发一下吧 感谢

**Comment by markbanyang** [comment]
好的，稍等下。

**Comment by markbanyang** [comment]
[Uploading FileDownloadController.java.zip…]()
文件信息：
![Uploading image.png…]()

jvm启动参数：
![Uploading image.png…]()

**Comment by wangzihaogithub** [comment]
发的文件好像坏了， 看不到

**Comment by wangzihaogithub** [comment]
要不贴代码吧， 就需要启动参数和代码片段就行

**Comment by markbanyang** [comment]
我发你邮箱了

**Comment by markbanyang** [comment]
下载的文件信息：





jvm启动参数：



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangzihaogithub/spring-boot-protocol"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月5日(星期六) 下午4:19
收件人:&nbsp;"wangzihaogithub/spring-boot-protocol"<spring-boot-protocol@noreply.github.com&gt;;
抄送:&nbsp;"tntym"<2236350912@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wangzihaogithub/spring-boot-protocol] FileUpload OutOfDirectMemoryError (#12)





 
辛苦发一下吧 感谢

**Comment by wangzihaogithub** [comment]
复现了， 我改下。

**Comment by markbanyang** [comment]
好的

**Comment by wangzihaogithub** [comment]
解决了， 这是netty的bug，已经修复了在master分支了。 后续pull-request 给netty。

修复netty的写失败后，没有再重试的bug。会导致下次无法再写入数据。

https://github.com/wangzihaogithub/spring-boot-protocol/commit/af43b8977adbb5dec65571369e9bd213ab8cc301

https://github.com/netty/netty/issues/10353

**Comment by wangzihaogithub** [comment]
netty before

`

                    int attemptedBytes = buffer.remaining();
                    final int localWrittenBytes = ch.write(buffer);
                    if (localWrittenBytes <= 0) {
                        incompleteWrite(true);
                        return;
                    }
                    adjustMaxBytesPerGatheringWrite(attemptedBytes, localWrittenBytes, maxBytesPerGatheringWrite);
                    in.removeBytes(localWrittenBytes);
                    --writeSpinCount;
`

netty after

`

                    final int localWrittenBytes = ch.write(buffer);
                    if (localWrittenBytes <= 0) {
                        incompleteWrite(true);
                    }else {
                        adjustMaxBytesPerGatheringWrite(attemptedBytes, localWrittenBytes, maxBytesPerGatheringWrite);
                        in.removeBytes(localWrittenBytes);
                    }
                    --writeSpinCount;

`

**Comment by markbanyang** [comment]
使用commons-fileupload上传文件，以流的方式读取上传的数据，这个过程也是需要等上传的数据发送完成暂存在本地，才会到controller层处理么。直接读取流数据的方式上传文件，可不可以做到不在本地暂存一份。

**Comment by wangzihaogithub** [comment]
可以， 我改下。 
不过这种模式和servlet的模式冲突(因为servlet要求解析)， 我打算加个配置参数，让你可以选择开启或关闭。

**Comment by markbanyang** [comment]
这个配置可以通过 重写spring提供CommonsMultipartResolver的来处理么：
`public class CommonsMultipartResolverForProgress extends CommonsMultipartResolver {

	@Override
	public boolean isMultipart(HttpServletRequest request) {
		// h5文件上传时不进入处理
		if (request.getRequestURI().startsWith("/stream-upload-test")) {
			return false;
		}
		return super.isMultipart(request);
	}

}
`

**Comment by wangzihaogithub** [comment]
你改这一处不够， spring还会调用 getParameter， 导致触发解析body。

**Comment by wangzihaogithub** [comment]
改好了，在master分支， 你可以重写spring提供CommonsMultipartResolver的来处理了。
这是这次改动， https://github.com/wangzihaogithub/spring-boot-protocol/commit/603ce3a4159095f6d63b26480145c01cd001fd11

如果你需要在maven中央仓库中， 需要我发新版本，可以直接告诉我，我就发新版了。

**Comment by markbanyang** [comment]
还需要什么额外的特殊配置么，用你的测试代码是生效了，在我的环境里面依赖的master的代码，没有生效。

**Comment by wangzihaogithub** [comment]
需要你从我这的master分支, 同步一下代码. 或者我上传到中央仓库,

**Comment by wangzihaogithub** [comment]
idea的git 有个 remote的选项, 把我这个项目加进去, 然后merge into到你的分支就行

**Comment by markbanyang** [comment]
我拉取的master代码到本地，是下面这个提交么：
![image](https://user-images.githubusercontent.com/48742762/101245219-213fcd80-3746-11eb-8c94-55e8fb522851.png)

**Comment by wangzihaogithub** [comment]
是的

**Comment by markbanyang** [comment]
嗯 我是拉下来最新的代码做的测试，测试代码跟你应该是一致的。

**Comment by wangzihaogithub** [comment]
要不麻烦下,  你断点到 ServletInputStreamWrapper#awaitDataIfNeed 方法上, 看是哪个方法触发了阻塞解析.

**Comment by wangzihaogithub** [comment]
你是不是这个类 CommonsMultipartResolver, 没有正确执行啊.

**Comment by markbanyang** [comment]
我断点了下，主要在com.github.netty.protocol.servlet.NettyMessageToServletRunnable#onMessage这个方法上代码会有半分钟时间，还没有执行到CommonsMultipartResolver跟ServletInputStreamWrapper#awaitDataIfNeed 方法上

**Comment by wangzihaogithub** [comment]
哦哦 发现了, 这是个bug, 刚提交了, 你再拉下代码

**Comment by markbanyang** [comment]
好的

**Comment by markbanyang** [comment]
目前的数据处理是否缺少tcp的负反馈机制。
从最外层的表现看：以下载文件举例，当请求端不读取数据时，ServletOutputStream的write方法不会阻塞。

netty启动时的高水位设置为Integer.MAX_VALUE， 导致com.yunanbao.webserver.core.util.ChunkedWriteHandler#doFlush0 在判断channel.isWritable()永远为true，而导致队列一直增加。

将netty的高水位设置为1M时，下载一个大文件，但请求端不读取时会发生pointer being freed was not allocated错误，导致系统崩溃

**Comment by markbanyang** [comment]
是不是应该当阻塞的处理放到com.yunanbao.webserver.protocol.servlet.ServletOutputStream#writeHttpBody这个方法中，简单修改代码测试了下：
![image](https://user-images.githubusercontent.com/48742762/101610859-c0fda400-3a43-11eb-9426-6215e696e79a.png)

**Comment by wangzihaogithub** [comment]
可以先这样解决,  只要不触发netty的取消OP_WRITE, 就不会有问题. 

不过发文件, 建议你用NettyOutputStream#write(file), 一直read and write, 现在的bug比较多.  正在找办法从根源解决.

**Comment by wangzihaogithub** [comment]
一旦把网卡写繁忙一次, 后续这个tcp链接就会卡住, 直到你停止write.

**Comment by markbanyang** [comment]
好的

**Comment by markbanyang** [comment]
上面那个方式也解决不了，网卡写繁忙一次就在也写不了数据了

**Comment by markbanyang** [comment]
这个问题后面会解决么

**Comment by wangzihaogithub** [comment]
会，不过可能要下周开始解决了， 这周工作有些忙

**Comment by markbanyang** [comment]
好的

**Comment by wangzihaogithub** [comment]
已经在master分支解决了, 同时发布了2.1.0版本.

**Comment by markbanyang** [comment]
好的  我验证下
