### ISSUE TITLE
大佬，出现NettyX-Server-Worker-Epoll这个问题是啥原因呀?

### ISSUE THREAD

**Issue by QianCYang** [wangzihaogithub/spring-boot-protocol#36]
[NettyX-Server-Worker-Epoll-4-4] c.g.n.p.s.DispatcherChannelHandler       : handler exception. case=io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer, channel=[id: 0xd09192e2, L:/192.123.1.78:5783 - R:/192.168.90.187:56221]

**Comment by wangzihaogithub** [comment]
客户端连接上服务器了，准备开始读内容，但是突然tcp连接被服务器突然close了

**Comment by wangzihaogithub** [comment]
我下个版本，把这类异常去掉

**Comment by QianCYang** [comment]
```
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259) ~[netty-buffer-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:553) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
	at com.github.netty.core.util.NettyThreadX.run(NettyThreadX.java:50) ~[classes/:na]
```

我在本地idea 启动了com.github.netty.http.HttpBootstrap 这个测试Springboot项目
然后另一个项目 通过
String forObject = restTemplate.getForObject("http://localhost:8080/test/hello?name=xiaowang", String.class);访问

随着另一个项目的关闭会出现上面的报错，报错率是100%的

**Comment by QianCYang** [comment]
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401) ~[na:na]
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434) ~[na:na]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259) ~[netty-buffer-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-buffer-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:553) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
	at com.github.netty.core.util.NettyThreadX.run(NettyThreadX.java:50) ~[classes/:na]

我在本地idea 启动了com.github.netty.http.HttpBootstrap 这个测试Springboot项目
然后另一个项目 通过
String forObject = restTemplate.getForObject("http://localhost:8080/test/hello?name=xiaowang", String.class);访问

随着另一个项目的关闭会出现上面的报错，报错率是100%的

**Comment by wangzihaogithub** [comment]
项目的关闭时，你应该还有正在读数据的请求还没执行完

**Comment by wangzihaogithub** [comment]
这个错误没影响，tomcat也有这个错误，应该log级别比较低，所以平时不会注意。

**Comment by QianCYang** [comment]
哦哦哦，好的

**Comment by QianCYang** [comment]
![image](https://github.com/wangzihaogithub/spring-boot-protocol/assets/28778036/5b88e108-4d80-4fe4-aa8d-4990871db602)
可以通过啥配置避免出现该问题吗？我这边一出现就是一大堆哦

**Comment by QianCYang** [comment]
> ![image](https://private-user-images.githubusercontent.com/28778036/340571508-5b88e108-4d80-4fe4-aa8d-4990871db602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTQ3ODEsIm5iZiI6MTcxODY5NDQ4MSwicGF0aCI6Ii8yODc3ODAzNi8zNDA1NzE1MDgtNWI4OGUxMDgtNGQ4MC00ZmU0LWFhOGQtNDk5MDg3MWRiNjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA3MDgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZTcwMWFiYTlhZmZkMmUwN2NhYzJjMzI0MjBmNDcyNTUyOTZmMTE5Mzg3Zjc1NjEwNmExYzc5NDJmMWIwNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ILoYd8VOH0fPEazQUHoCFwiL1qIfofcsQsG7CJjjT7U) 可以通过啥配置避免出现该问题吗？我这边一出现就是一大堆哦

是这样处理吗？
![image](https://github.com/wangzihaogithub/spring-boot-protocol/assets/28778036/f5526147-04ec-42ab-adc4-46ba7921514b)

**Comment by wangzihaogithub** [comment]
我是这样改的 


           if (cause.getClass().getName().startsWith("io.netty.handler.codec.http2")) {
                      // ignore
                  } else if (IOException.class.isAssignableFrom(cause.getClass())) {
                      if (logger.isDebugEnabled()) {
                          logger.debug("handler IOException. case={}, channel={}", cause.toString(), context.channel(), cause);
                      }
                  } else {
                      logger.warn("handler exception. case={}, channel={}", cause.toString(), context.channel(), cause);
                  }

**Comment by wangzihaogithub** [comment]
已经在2.3.19解决

https://github.com/wangzihaogithub/spring-boot-protocol/pull/38
